CREATE USER IF NOT EXISTS 'monitor'@'%' IDENTIFIED BY 'monitor';

CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY 'password' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';

CREATE USER IF NOT EXISTS 'slave_user'@'%' IDENTIFIED BY 'password';
GRANT REPLICATION SLAVE ON *.* TO 'slave_user'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

CREATE TABLE users (
    id INT AUTO_INCREMENT,
    name VARCHAR(255) NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

INSERT INTO users VALUES (1, 'anisur'), (2, 'sakib');